# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 3D Art Blog
email: lauredemey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog where I post some 3D models I make. I'm new to 3D and I try to improve my skills by posting a new model here every week.   
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lauredm.github.io" # the base hostname & protocol for your site
twitter_username: Laure_DeMey
github_username:  LaureDM

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
